[package]
name = "intertest"
version = "0.1.2"
authors = ["Peng Guanwen <pgw1999@outlook.com>"]

[dependencies]
os_pipe = "*"
clap = {version = "*", features = ["yaml"]}
clippy = {version = "*", optional = true}

[features]
default = []
